//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroNegocios.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgroNegocios.Resources.HomeRes", typeof(HomeRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGRO-NEGOCIOS ltd Is a group of Israel&apos;s leading companies for the design, engineering, distributing and installation of agriculture projects around the world. AGRO-NEGOCIOS primary mission is to develop economically viable agricultural and a Aquaculture and livestock infrastructure projects that enhance the quantity and quality of production around the world..
        /// </summary>
        public static string AgroStory {
            get {
                return ResourceManager.GetString("AgroStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create jobs.
        /// </summary>
        public static string Createjobs {
            get {
                return ResourceManager.GetString("Createjobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local are trained and employed..
        /// </summary>
        public static string CreatejobsDesc {
            get {
                return ResourceManager.GetString("CreatejobsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact Planning.
        /// </summary>
        public static string ExactPlanning {
            get {
                return ResourceManager.GetString("ExactPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Support.
        /// </summary>
        public static string FinancialSupport {
            get {
                return ResourceManager.GetString("FinancialSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensures the most cost-effective solution in addition to return on investments and long-term results. We can offer offtake agreement in some parts of the world to some of our products..
        /// </summary>
        public static string FinancialSupportDesc {
            get {
                return ResourceManager.GetString("FinancialSupportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest standards of.
        /// </summary>
        public static string HighestStandards {
            get {
                return ResourceManager.GetString("HighestStandards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equipment, materials, and constructions..
        /// </summary>
        public static string HighestStandardsDesc {
            get {
                return ResourceManager.GetString("HighestStandardsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impact Projects.
        /// </summary>
        public static string ImpactProjects {
            get {
                return ResourceManager.GetString("ImpactProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With over 40 years of experience, we bring reliable field-proven technology, backed by professional expertise and knowledge to agriculture large-scale project..
        /// </summary>
        public static string ImpactProjectsDesc {
            get {
                return ResourceManager.GetString("ImpactProjectsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation &amp; Support.
        /// </summary>
        public static string ImplementationAndSupport {
            get {
                return ResourceManager.GetString("ImplementationAndSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A successful project comes to an end when the client has all the knowledge required to continue the project successfully. Professional and technical support will be available to the customer throughout the project period and beyond if required..
        /// </summary>
        public static string ImplementationAndSupportDesc {
            get {
                return ResourceManager.GetString("ImplementationAndSupportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training and knowledge transfer are key to the success of each project. Relevant knowledge is provided in the OJT courses and until the completion of the full project implementation..
        /// </summary>
        public static string InstructionsDesc {
            get {
                return ResourceManager.GetString("InstructionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration.
        /// </summary>
        public static string Integration {
            get {
                return ResourceManager.GetString("Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different projects require different systems (irrigation, climate control, water treatment, etc.). We ensure that all systems are computerized, controlled and integrated to one working system..
        /// </summary>
        public static string IntegrationDesc {
            get {
                return ResourceManager.GetString("IntegrationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let Us.
        /// </summary>
        public static string LetUs {
            get {
                return ResourceManager.GetString("LetUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skilled professionals who accompany the project from its first day and provide a comprehensive holistic solution for all needs..
        /// </summary>
        public static string ManagementDesc {
            get {
                return ResourceManager.GetString("ManagementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Projects.
        /// </summary>
        public static string OurProjects {
            get {
                return ResourceManager.GetString("OurProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our vision.
        /// </summary>
        public static string OurVision {
            get {
                return ResourceManager.GetString("OurVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In today&apos;s world, we understand that food security, clean water and energy are complex and different in each part of the world. Our goal is to find the tailor solution to the challenges we are facing with. Our unique way of integrated methods, Innovative systems and experience allow us to learn how to increase productivity and improve conditions considering all existing status and turn them into success stories..
        /// </summary>
        public static string OurVisionDesc {
            get {
                return ResourceManager.GetString("OurVisionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Developments.
        /// </summary>
        public static string ProductDevelopments {
            get {
                return ResourceManager.GetString("ProductDevelopments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUICK LINKS.
        /// </summary>
        public static string QuickLinks {
            get {
                return ResourceManager.GetString("QuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce energy.
        /// </summary>
        public static string ReduceEnergy {
            get {
                return ResourceManager.GetString("ReduceEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costs, chemicals, repairs, and maintenance..
        /// </summary>
        public static string ReduceEnergyDesc {
            get {
                return ResourceManager.GetString("ReduceEnergyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenues.
        /// </summary>
        public static string Revenues {
            get {
                return ResourceManager.GetString("Revenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase commercial efficiency..
        /// </summary>
        public static string RevenuesDesc {
            get {
                return ResourceManager.GetString("RevenuesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainable development.
        /// </summary>
        public static string SustainableDevelopment {
            get {
                return ResourceManager.GetString("SustainableDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meeting human development goals while at the same time sustaining the ability of natural systems to provide..
        /// </summary>
        public static string SustainableDevelopmentDesc {
            get {
                return ResourceManager.GetString("SustainableDevelopmentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string Technology {
            get {
                return ResourceManager.GetString("Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete systems supply, most systems are in-house developments, so we can carry out modifications, creative and flexible engagement models on the basis of each project, so each project receives its needs accurately and allows us to increase production, reduce water waste and so..
        /// </summary>
        public static string TechnologyDesc {
            get {
                return ResourceManager.GetString("TechnologyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Transfer.
        /// </summary>
        public static string TechnologyTransfer {
            get {
                return ResourceManager.GetString("TechnologyTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell You Our Story.
        /// </summary>
        public static string TellYouOurStory {
            get {
                return ResourceManager.GetString("TellYouOurStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Best Way.
        /// </summary>
        public static string TheBestWay {
            get {
                return ResourceManager.GetString("TheBestWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Contact Us.
        /// </summary>
        public static string ToContactUs {
            get {
                return ResourceManager.GetString("ToContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training And Knowledge.
        /// </summary>
        public static string TrainingAndKnowledge {
            get {
                return ResourceManager.GetString("TrainingAndKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Key Projects.
        /// </summary>
        public static string TurnKeyProjects {
            get {
                return ResourceManager.GetString("TurnKeyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/watch?v=GpUo7bPPvgw.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Methods.
        /// </summary>
        public static string WorkingMethods {
            get {
                return ResourceManager.GetString("WorkingMethods", resourceCulture);
            }
        }
    }
}
